version: '3.8'

services:
  nl2sql:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Database configuration
      - DB_CONNECTION_STRING=mssql+pyodbc://username:password@sqlserver/database?driver=ODBC+Driver+18+for+SQL+Server
      - DB_MAX_POOL_SIZE=10
      - DB_TIMEOUT=30
      
      # LLM configuration
      - LLM_PROVIDER=local  # or 'openai'
      - LLM_LOCAL_MODEL=mistral
      - LLM_LOCAL_URL=http://ollama:11434
      - LLM_OPENAI_API_KEY=  # Set if using OpenAI
      - LLM_TEMPERATURE=0.1
      - LLM_MAX_TOKENS=1000
      
      # Vector database configuration
      - VECTOR_PERSIST_DIRECTORY=/app/chromadb
      - VECTOR_COLLECTION_NAME=schema_embeddings
      - VECTOR_EMBEDDING_MODEL=all-MiniLM-L6-v2
      - VECTOR_TOP_K=5
      
      # Application configuration
      - APP_DEBUG=false
      - APP_LOG_LEVEL=INFO
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    
    volumes:
      - ./chromadb:/app/chromadb
      - ./logs:/app/logs
      - ./schema.json:/app/schema.json:ro
    
    depends_on:
      - ollama
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    
    # Uncomment the following lines if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Optional: SQL Server for testing
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  ollama_data:
    driver: local
  sqlserver_data:
    driver: local

networks:
  default:
    name: nl2sql-network
